// A Unit Called <ASCII.H>

#define UPARROW 72
#define DOWNARROW 80
#define LEFTARROW 75
#define	RIGHTARROW 77
#define INS 82
#define DEL 83
#define BACKSPACE 8
#define TAB 9
#define HOME 71
#define END 79
#define PGUP 73
#define PGDN 81
#define ESC 27
#define RET 13
#define ALTX 45
#define F1  59
#define F2  60
#define F3  61
#define F4  62
#define F5  63
#define F6  64
#define F7  65
#define F8  66
#define F9  67
#define F10 68